/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriverHomeRouteImport } from './routes/driver.home'
import { Route as DriverNavigationRouteImport } from './routes/driver.navigation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverHomeRoute = DriverHomeRouteImport.update({
  id: '/driver/home',
  path: '/driver/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverNavigationRoute = DriverNavigationRouteImport.update({
  id: '/driver/navigation',
  path: '/driver/navigation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/driver/home': typeof DriverHomeRoute
  '/driver/navigation': typeof DriverNavigationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/driver/home': typeof DriverHomeRoute
  '/driver/navigation': typeof DriverNavigationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/driver/home': typeof DriverHomeRoute
  '/driver/navigation': typeof DriverNavigationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/driver/home' | '/driver/navigation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/driver/home' | '/driver/navigation'
  id: '__root__' | '/' | '/driver/home' | '/driver/navigation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DriverHomeRoute: typeof DriverHomeRoute
  DriverNavigationRoute: typeof DriverNavigationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/home': {
      id: '/driver/home'
      path: '/driver/home'
      fullPath: '/driver/home'
      preLoaderRoute: typeof DriverHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/navigation': {
      id: '/driver/navigation'
      path: '/driver/navigation'
      fullPath: '/driver/navigation'
      preLoaderRoute: typeof DriverNavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DriverHomeRoute: DriverHomeRoute,
  DriverNavigationRoute: DriverNavigationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
